# Render Blueprint - Infrastructure as Code
# This is the official way to override Render's auto-detection

services:
  - name: traffic-management
    type: web
    runtime: python
    plan: free
    region: oregon
    
    # Build configuration
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    
    # CRITICAL: This overrides auto-detection
    startCommand: python start.py
    
    # Environment variables
    envVars:
      - key: RENDER
        value: "true"
      - key: VIN_PRODUCTION_MODE  
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"