# Render Blueprint - Infrastructure as Code
# FORCE: Disable all auto-detection and use our production system

services:
  - name: traffic-management
    type: web
    runtime: python
    plan: free
    region: oregon
    
    # Build configuration - install dependencies without streamlit
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    
    # FORCE: Explicit start command - NO AUTO-DETECTION
    startCommand: python main.py
    
    # Disable auto-detection features
    autoDeploy: false
    
    # Environment variables
    envVars:
      - key: RENDER
        value: "true"
      - key: VIN_PRODUCTION_MODE  
        value: "true"
      - key: PYTHON_VERSION
        value: "3.11"
      - key: DISABLE_STREAMLIT_AUTO_DETECTION
        value: "true"