[theme]
# Subtle dark theme tuned for the dashboard
primaryColor = "#3b82f6"
backgroundColor = "#0f172a"
secondaryBackgroundColor = "#1e293b"
textColor = "#f1f5f9"
font = "sans serif"

[server]
enableCORS = false
headless = true
